#!/usr/bin/env bash




##
## ## Desktop Background Image
##

hyprpaper &
#~/.azotebg &
#wf-background &
#pcmanfm-qt --desktop --daemon-mode &




##
## ## Polkit
##

/usr/libexec/xfce-polkit &




##
## ## wf-shell
##

wf-panel &




##
## ## nm-applet
##

nm-applet &




##
## ## fcitx5
##

fcitx5 &
